### PR TITLE
Require requests >= 2.4.3

### PR DESCRIPTION
**Pull request by yuvipanda**
- Is available on debian jessie onwards, makes packaging
  easier
- No particular features that were introduced in newer
  version of requests seems to be used

### CODE REVIEW

**Comment by andsens** [comment]
@tiago, could you sign off on this? Seems sensible to me.

**Comment by myhro** [comment]
Well, Anders, looks like you asked another Tiago but... Seems reasonable to me as well. :-)

**Comment by andsens** [comment]
Hah, it's late here. I think I'll just merge and go to bed :-)
Thanks for the fix @yuvipanda!

**Comment by yuvipanda** [comment]
Thank you :D

On Thu, Mar 24, 2016 at 4:29 PM, Anders Ingemann <notifications@github.com>
wrote:

> Merged #307 <https://github.com/andsens/bootstrap-vz/pull/307>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/andsens/bootstrap-vz/pull/307#event-602487047>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Pull request merged**
