### PR TITLE
Add support for Debian 8 in GCE.

### PR DESCRIPTION
**Pull request by zmarano**
Add jessie and jessie-backports manifests, rename wheezy manifests.
Add support for GPT disks in GCE.
Change the default block scheduler to noop for improved persistent disk performance on GCE.

### CODE REVIEW

**Comment by myhro** [comment]
Hi Zach,

Although I would like to see those changes in different PRs, I guess it's not really a problem to merge it all together. But before doing this, I have to ask some questions (and hear @andsens opinions too):

> Change the default block scheduler to noop for improved persistent disk performance on GCE.

Should we use `elevator=noop` only for GCE? Or is it a good idea to also enable it every provider? Maybe for every bootstrapped image that uses GRUB? Extlinux also supports it?

> Add jessie and jessie-backports manifests, rename wheezy manifests.

The manifests folder is getting a little messy with so many files. Tomasz [suggested splitting this directory][1] back in July 2014 and Anders [remembered this in the last month][2]. Maybe the time to that has come? :-)

[1]: https://lists.debian.org/debian-cloud/2014/07/msg00026.html
[2]: https://lists.debian.org/debian-cloud/2015/04/msg00026.html

**Comment by zmarano** [comment]
Hi Tiago,
I can't speak to other provider's disk performance- only to GCE and what our own persistent disk engineers have recommended we do. Therefore, I really don't know if noop would help or hinder other cloud providers disk performance so I don't feel comfortable suggesting that change elsewhere.

For manifests, you are suggesting it should be like providers... so manifests/gce/... right. I think that is a good idea but I wouldn't want to make that change in this PR which is GCE specific.

**Comment by myhro** [comment]
Zach,

> I think that is a good idea but I wouldn't want to make that change in this PR which is GCE specific.

I agree. I'm in no way telling that this is your responsibility. What happened is that your PR opened a few possibilities that can be useful for other providers as well. So, instead of opening new issues to discuss them, I'm using this space to talk about it while the topic is still fresh.

Let's just wait a few hours/days until Anders appears here (I don't know if he's back from vacation). If he don't shows up anytime soon, I'll test/merge this PR and open new issues regarding the questions on my first reply.

Thanks in advance!

> (...) our own persistent disk engineers have recommended we do.

P.s.: Sometimes I forgot how big Google is, so it can afford specialized engineers like that. :-)

**Comment by zmarano** [comment]
No worries :) Also, I'm quite happy everything is merged back to master now- it makes building images easier for us. Thanks for that!

**Comment by andsens** [comment]
Heyo :-)
So yeah, first of all thanks for the PR, it looks really good.
I think we should just merge this and clean up the manifest folder afterwards. @zmarano, I assume this is properly tested? The changes don't look too radical, though if you'd like to give it a spin @myhro it'd be awesome (I don't have the time right now unfortunately), otherwise just go ahead and merge - things look good to me.

I opened #221 to track the change regarding the block scheduler.

p.s.: @zmarano, any idea whether you and your buddies at google would like to get on the integration testing train anytime soon? It works quite well for both virtualbox and ec2 already, though there is of course always some work to do (right now it only checks if instances boot successfully).

**Comment by zmarano** [comment]
Hi,
Yes, I've tested this for our images here.

Sure, I'd be happy to take a look at integration testing- send me whatever info you have and I'll be happy to take a look.

**Comment by myhro** [comment]
Anders,

> I think we should just merge this and clean up the manifest folder afterwards.

Agreed. Can we discuss the naming convention when you are back? Or should we do that on the debian-cloud mailing list instead?

> The changes don't look too radical, though if you'd like to give it a spin @myhro it'd be awesome (I don't have the time right now unfortunately), otherwise just go ahead and merge - things look good to me.

He already tested the changes and they look fine to me either, so I'll merge them.

> I opened #221 to track the change regarding the block scheduler.

Thank you! :-)

-

Zach,

> Also, I'm quite happy everything is merged back to master now- it makes building images easier for us. Thanks for that!

Actually the idea of doing this came when I talked to another googler, Eric Johnson. I've discussed the matter with Anders and now we have everything on `master`. It's good to see that you liked it.

> Sure, I'd be happy to take a look at integration testing- send me whatever info you have and I'll be happy to take a look.

We have an [Integration tests][1] section on our documentation.

Thanks again, Zach! Merging...

[1]: https://bootstrap-vz.readthedocs.org/en/master/testing/integration_tests.html

**Comment by zmarano** [comment]
Yeah I work with Eric Johnson and we're both very happy about having a
merged master branch :) Thanks guys!

-----
Zach Marano
zmarano@google.com
Cell: +1 805-403-8526

**Pull request merged**
