### PR TITLE
Fix ephemeral mounts

### PR DESCRIPTION
**Pull request by zeridon**
Add all possible ephemeral block mounts during AMI registration

Value for this being if not using directly AWS to launch a server (ergo skipping the assignment).

Prime case is Rightscale: they create their images with 1-4 ephemeral mounts. Due to this on some instance sizes you don't see all the available ephemeral storage and there is no way to add it afterwards.

### CODE REVIEW

**Comment by zeridon** [comment]
Unfortunately i have to retract the pull

**Comment by andsens** [comment]
How so? What changed?

**Comment by udangel-r7** [comment]
any idea why this was removed? i am looking for something similar atm

**Comment by andsens** [comment]
@udangel-r7 we're talking more than 2 years ago man, no clue :-/

**Pull request closed without merging**
