### PR TITLE
Remove support for the GCE Debian mirror.

### PR DESCRIPTION
**Pull request by illfelder**

### CODE REVIEW

**Comment by myhro** [comment]
Hi Max,

The GCE mirror was (or is going to be) discontinued?

**Comment by illfelder** [comment]
We are starting the deprecation process for the GCE Debian mirror - removing references to it in future images is the first step.

**Comment by myhro** [comment]
Thanks for the clarification. Merging... :-)

**Comment by illfelder** [comment]
Awesome! Thanks!

**Pull request merged**
