### PR TITLE
Promote stretch to stable, add buster as testing, jessie to oldstable.

### PR DESCRIPTION
**Pull request by zmarano**
Stretch release to stable is June 17(tonight/tomorrow depending on time zone).

### CODE REVIEW

**Comment by andsens** [comment]
Woops, tests failing. These need fixing: [tests/unit/releases_tests.py](https://github.com/andsens/bootstrap-vz/blob/c23e73c2223a9e4f25615078b384b2e32b5f141d/tests/unit/releases_tests.py#L25-L34)

**Comment by zmarano** [comment]
Oh yeah, tests ;) Fixed!

**Comment by andsens** [comment]
Nice 👍 
I'll fix these myself :-)
```
def test_not_identity():
    assert releases.wheezy is not releases.stable
    assert releases.stable is not releases.jessie
```
And maybe document the idea behind them :-)

**Comment by zmarano** [comment]
Yeah I saw those- I don't really understand why those work because ```assert releases.stable is not releases.jessie``` should have failed before.

**Comment by andsens** [comment]
It shouldn't. It's an identity check `==` is not the same as `is`.  
So `stable == jessie` and `stable is stable` but `stable is not jessie`. Not sure if that clears it up or adds confusion.

**Comment by zmarano** [comment]
I see what you're saying- but yeah its still really confusing :)

**Pull request merged**
