### PR TITLE
manifest: Validate schemata before use

### PR DESCRIPTION
**Pull request by nbraud**
This modifies `manifest.schema_validator` (which is passed as argument to all the `validate_schema` functions) to:
- first validate the schema against the JSON metaschema;
- then validate the manifest against the schema.

This is probably suboptimal, as the metaschema is reloaded every time, but I noticed no significant impact.

### CODE REVIEW

**Comment by andsens** [comment]
Great idea! Regarding the reloading, you could just load the metaschema in `__init__`.

**Comment by nbraud** [comment]
I wasn't sure it was worth doing, but on the other hand it is basically a 2 line patch.
¯\_(ツ)_/¯

**Comment by andsens** [comment]
Nice. If you could fix the test failures, I'll merge
```
bootstrapvz/base/manifest.py:31:31: F821 undefined name 'os'
bootstrapvz/base/manifest.py:31:48: F821 undefined name 'os'
bootstrapvz/base/manifest.py:31:61: F821 undefined name 'os'
bootstrapvz/base/manifest.py:126:3: F401 'os' imported but unused
```

**Comment by nbraud** [comment]
Looks like I managed to test in the wrong branch...

**Comment by andsens** [comment]
Merging...

**Pull request merged**
