### PR TITLE
admin_user plugin: Fix non-EC2 behaviour

### PR DESCRIPTION
**Pull request by nbraud**
Currently, `admin_user` attempts to add the task `AdminUserPublicKeyEC2` if no pubkey is specified, which results in an error if the provider is not EC2.

This patch introduces an additional check, and simply sets no public key if none is defined and the provider is not EC2.

### CODE REVIEW

**Comment by andsens** [comment]
I see the problem, but shouldn't we fail if no authentication method is provided? Maybe check if neither a password nor a pubkey is set?

**Comment by nbraud** [comment]
@andsens That's not obvious: for instance, I ran into this issue while building a VM for a lecture, where students get automatically logged-in as the user in the GUI.
There, I do not necessarily want to have a password set.

**Comment by andsens** [comment]
Ah. That makes sense. Hm ok, I still think we should issue a warning à la "You have not provided any authentication method for the admin user {username}". Your use-case makes sense to support (because you can add a dozen other auth methods in any number of ways), but I would guess that 90% of the time it is a mistake in the manifest, so it's better to issue one warning too much than to little.

**Comment by nbraud** [comment]
@andsens Makes sense.

**Comment by nbraud** [comment]
@andsens Warnings added

**Comment by andsens** [comment]
Nice, looks great. You forgot to import the logging package though, and there is a pep8 error (you can check that locally with `tox -e flake8`).

**Comment by nbraud** [comment]
@andsens Fixed.

**Comment by andsens** [comment]
Yup! Perfect. Merging...

**Pull request merged**
