### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by andrewbogott**
Lots of lint fixes -- this should get the master branch passing Travis again :)

### CODE REVIEW

**Comment by andsens** [comment]
Dang! Nice job! Regarding the `\\d` escaping, wouldn't it be easier to just make the string literals raw? As in `r'\d'`?

**Comment by andrewbogott** [comment]
> wouldn't it be easier to just make the string literals raw? As in r'\d'

It might.  I thought I saw some mixed-case examples in there where we had both expanded and non-expanded escapes, but I'll look again and see if that's right.

**Comment by andrewbogott** [comment]
Yeah, there are a couple of ugly cases which mix valid and invalid escapes:

'127.0.0.1\s*{hostname}\n?'

and

'^\troot \(hd0\)$'

I'm going to use double-bashes for those and r'' for the clearer cases.

**Comment by andrewbogott** [comment]
I have another patch ready that addresses those mixed cases... I think they're probably just in error but I don't want to include those changes in this PR since they're (maybe) bugfixes rather than no-ops.

**Comment by andsens** [comment]
Looks great! Merging...

**Pull request merged**
