### PR TITLE
Enable setting `apt.conf(5)` options

### PR DESCRIPTION
**Pull request by KellerFuchs**
This adds the possibility of adding configuration snippets in `apt.conf` and `apt.conf.d`:
```yaml
packages:
    apt.conf.d:
        00InstallRecommends:  >-
            APT::Install-Recommends "false";
            APT::Install-Suggests   "false";
```

Those settings are applied before packages get installed, making it viable to set things like `APT::Install-Recommends` or `Acquire::http::Proxy`.

Moreover, 2 fixup commits are included.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Do not merge yet, this is untested.

**Comment by andsens** [comment]
Hi @KellerFuchs. Quoting the dev guidelines:
> Please try to be very descriptive about your changes when you write a pull request, stating what it does, **why it is needed**, **which use cases this change covers**, etc

Could you elaborate on the use case?
Also, maybe you could add an example to the docs on how to use the setting.

p.s.: Thanks for the fixes in the documentation.

**Comment by KellerFuchs** [comment]
@andsens Thanks for the feedback.  I added a quick description here, and an example in the example manifest in the docs.

**Comment by KellerFuchs** [comment]
@andsens Is there anything else missing in that PR?

**Comment by andsens** [comment]
Nope. I'll try it out tomorrow and merge if all's well :-)

**Comment by KellerFuchs** [comment]
@andsens Thanks a lot for reviewing.

**Comment by andsens** [comment]
My apologies @KellerFuchs, testing #294 takes quite som time and I try to treat PRs in a FIFO manner, so it's going to be a while before I can test and then merge this (unless @myhro can help?)

**Comment by myhro** [comment]
Hi Anders,

> unless @myhro can help?

Yes I can, albeit this pull request is so carefully crafted that I have almost nothing to ask for a fix. The only part that I didn't quite understood was the change from `minItems` to `minProperties` the base manifest schema.

@KellerFuchs can you please take care of the following items?

* Fix the "8-spaces indentation". We are still asking for "[indent with tabs and align with spaces][1]" in the coding style guidelines, but I've talked with Anders about moving from tabs to 4-spaces indentation in the near future and a few PRs have been accepted this way already. So, it's OK if you go from 8 to 4 spaces indentation instead of tabs right now.
* Rebase it on top of `master`. Right now it is 3 commits behind.
* The last one is not a must, but would be nice if we change the example of `10proxy`. I like the idea of having another entry as an example of a single-line file (which doesn't needs `>-` in its syntax), but we already have the [apt_proxy plugin][2]. It has an option to make the configuration persistent (to be used only during the bootstrap process or remain on the resulting image), can check if the server can be reached, has a nice syntax for `username`/`password`, etc. This way it will not look like we are encouraging the usage of a hand-made setting instead of a plugin designed specifically for this task.

Thanks for your great work!

Regards,
Tiago.

[1]: https://github.com/andsens/bootstrap-vz/blob/1b8749bd7fd36312918f9a4c68c39336a5a07971/CONTRIBUTING.rst#coding-style
[2]: https://github.com/andsens/bootstrap-vz/tree/1b8749bd7fd36312918f9a4c68c39336a5a07971/bootstrapvz/plugins/apt_proxy

**Comment by KellerFuchs** [comment]
@myhro As far as I understand, `minItems` is only good for arrays, [not for objects](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#size).
I will rebase and push fixes right now.

**Comment by KellerFuchs** [comment]
@myhro Done.

**Comment by myhro** [comment]
Many thanks, @KellerFuchs. As some files had their indentation changed in its entirety, I have to ask @andsens: do you see a problem with this? Or can we merge the PR in the current state?

I'm in favor for the later option, as we are going to change all of them anyway.

**Comment by andsens** [comment]
Well initially I'd say that we should preserve indentation until the change so that the changesets are readable, but honestly, the change to spaces indentation is going to screw that over anyways. You'll be able to blame all files and see my name on them, heh :-/

So this is fine, go ahead and merge.

**Comment by myhro** [comment]
> You'll be able to blame all files and see my name on them, heh :-/

Yeah, this is something that we can't get rid of... Thank you, Anders.

Thanks again, @KellerFuchs.

Merging...

**Comment by KellerFuchs** [comment]
@andsens @myhro Thanks a lot for reviewing.

**Pull request merged**
