### PR TITLE
Pylint code clean up

### PR DESCRIPTION
**Pull request by CMeza99**
* enable more pylint tests
* also fixes a cross-plugin dependency which was broken from a previous commit that moved a task to commons (prebootstrapped was calling task in dpkg)

### CODE REVIEW

**Comment by andsens** [comment]
Holy macaroni! That is impressive! I have checked the diff but couldn't find the fix you are talking about, care to elaborate that one?

**Comment by CMeza99** [comment]
I had actually forgot myself and need to go through and find the commit myself. Pylint E1101(no-member) caught it. The prebootstrapped plugin was calling task in the dpkg plugin which was moved to the common after I tried to the same thing. :)

https://github.com/andsens/bootstrap-vz/pull/471/commits/b180f66ef022631ba46849158940829dc0896db6#diff-4536f249c1c9a9eae6c99cbd62693afc

**Comment by CMeza99** [comment]
It is running in tox/travis now. https://travis-ci.org/andsens/bootstrap-vz/builds/374071447#L448, https://github.com/andsens/bootstrap-vz/blob/master/tox.ini#L11. :)

I figured I would leave flake8 there until the todo's were done. https://github.com/andsens/bootstrap-vz/pull/471/files#diff-7960115f72225be4a82e33b5a7857f5aL41 But if you prefer I can remove it.

**Comment by andsens** [comment]
Sorry about the delay, should've merged this long ago. Ah well, better late than never :-)

**Pull request merged**
