### PR TITLE
filesystem: Mount a tmpfs on /tmp

### PR DESCRIPTION
**Pull request by nbraud**
@brett-smith Could you confirm this solves the issue you had? (#322)

### CODE REVIEW

**Comment by andsens** [comment]
Ping @brett-smith. Does it make any difference?

**Comment by n3ph** [comment]
How would you define a size for the tmpfs?
I think of integrate this into #355

**Comment by andsens** [comment]
@n3ph this is only during bootstrapping, not when the machine is actually running. I am not sure your PR applies.

**Comment by andsens** [comment]
Closing this, due to inactivity. Feel free to reopen if it is still relevant and someone has tested this.

**Comment by nbraud** [comment]
@andsens Makes sense; @brett-smith can ask the PR to be reopened if their issue still exists.

**Pull request closed without merging**
