### PR TITLE
ENA support & migrate to boto3

### PR DESCRIPTION
**Pull request by andsens**
Mind if we merge this back @JamesBromberger & @vorlock?

[setup.py](https://github.com/andsens/bootstrap-vz/blob/876ea7bd85f97a674e9953c505d9b741b44ae831/setup.py#L26) needs to be update though.

### CODE REVIEW

**Comment by vorlock** [comment]
Above changes are almost in the state I'd be happy to merge, problem is there are still some small issues with tagging I think. We could merge it but it'll require some minor fixes, problem is atm I'm very busy at work.
I'll try to give it a last polish at the weekend but can't promise this on 100%, once it's done it should be ready to merge. I really planning to have it done rather earlier then later cause I want to upload it to Debian before total freeze, but ... .

**Comment by andsens** [comment]
Entirely understandable, give me a ping if you need som assistance, I'd be happy to help.

**Comment by vorlock** [comment]
@andsens at last I managed to finish what I wanted, setup.py has been updated as well I just didn't write tests for boto3 but beside this all is ok and working, so I think it should be ok to merge.

@JamesBromberger I think I'll merge what I did into deb and push it to Debian, there will be no version change as such (unless Anders will tag those changes as new release) and in such case it should be able to migrate, if not I'll back port it to Stretch once released, then just maintenance for Stretch live I suppose

**Comment by vorlock** [comment]
All should be sorted now, so lets merge it.

**Comment by andsens** [comment]
Whoa great work! Merging...  
I can tag a release if you'd like me to, no problem.

**Comment by vorlock** [comment]
Yeah, it makes sense ;-)

thx in advance

**Comment by andsens** [comment]
Alrighty then! I bumped the version to 0.9.11 and tagged it as such.

**Pull request merged**
