### PR TITLE
fix ^PermitRootLogin regex

### PR DESCRIPTION
**Pull request by aderumier**
fix issue https://github.com/andsens/bootstrap-vz/issues/218

### CODE REVIEW

**Comment by andsens** [comment]
Does this work on wheezy and squeeze? Is that line not commented out there?

**Comment by myhro** [comment]
I guess this is an use case that fits for a test to avoid regressions. :-)

**Comment by aderumier** [comment]
This is the same for squeeze/wheezy/jessie.

I never try bootstrap-vz with squeeze/wheezy, but the old regex before
https://github.com/andsens/bootstrap-vz/commit/2d3a0a0ce35e17dc183cf353ace2aed84f20accc
was using ^

**Comment by myhro** [comment]
This patch works for `squeeze`/`wheezy`/`jessie` indeed. The line he was talking about in #218 is:

    (...)
    # the setting of "PermitRootLogin without-password".
    (...)

Without the `^`, this line got replaced too.

I'll be merging and adding you to the changelog, Alexandre. Thank you!

**Pull request merged**
